# Configuration for the All-in-One Recon Tool

tools:
  subfinder:
    path: subfinder
  nmap:
    path: nmap
  httpx:
    path: httpx
  zaproxy:
    path: zaproxy # Path to the zap.sh script
  subzy:
    path: subzy
  nuclei:
    path: nuclei
  katana:
    path: katana
  ffuf:
    path: ffuf
    wordlist_dir: "/usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt"
    # Wordlist for Active Subdomain Enumeration (option 1)
    wordlist_subdomain: "/usr/share/seclists/Discovery/DNS/subdomains-top1million-20000.txt"
    # Wordlist for VHost Scanning (option 9)
    wordlist_vhost: "/usr/share/seclists/Discovery/DNS/namelist.txt"
